# Generated by Django 3.1.12 on 2024-11-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20241117_1740'),
    ]

    operations = [
    ]
