# Generated by Django 3.1.12 on 2024-11-17 17:54

from django.db import migrations

def drop_conversation_collection(apps, schema_editor):
    from conversation.models import Conversation
    # Conversation._meta.db_table.objects.all().delete()
    Conversation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20241117_1740'),
    ]

    operations = [
        migrations.RunPython(drop_conversation_collection)
    ]
